// Auto-generated by Convex — placeholder until `npx convex dev`.
// Do NOT edit this file manually; it is overwritten on every `npx convex dev`.

/* eslint-disable */

// Runtime placeholder: the real api object is generated by `npx convex dev`.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = {};
