// Auto-generated by Convex — placeholder until `npx convex dev`.
// Do NOT edit this file manually; it is overwritten on every `npx convex dev`.

/* eslint-disable */
export type Id<_T extends string> = string & { __tableName: _T };
export type DataModel = Record<string, unknown>;
export type Doc<_T extends string> = Record<string, unknown> & {
  _id: Id<_T>;
  _creationTime: number;
};
